// Stand-in for the Firestore listeners in §4.2. Swap for onSnapshot once the
// backend exists; the shapes are already the real ones.
import type { Ticket } from "./types"

const HOUR = 3_600_000
const ago = (hours: number) => Date.now() - hours * HOUR

let seq = 0
const id = (prefix: string) => `${prefix}-${++seq}`

export const MOCK_TICKETS: Ticket[] = [
  {
    ticketId: "TKT-20260908-0042",
    waNumber: "918827450192",
    contactName: "Sunita Devi",
    centreName: "AWC 42, Kolar Road, Bhopal",
    serviceId: "anganwadi-vr",
    serviceName: "Anganwadi VR",
    categoryId: "headset",
    categoryLabel: "Headset not working",
    language: "hi",
    description:
      "हेडसेट चालू नहीं हो रहा है। चार्ज करने पर भी लाल बत्ती जलती रहती है, हरी नहीं होती।",
    attachmentCount: 1,
    status: "open",
    slaState: "breached",
    resolution: null,
    createdAt: ago(51),
    updatedAt: ago(20.4),
    firstResponseAt: null,
    resolvedAt: null,
    closedAt: null,
    lastInboundAt: ago(20.4),
    messages: [
      { messageId: id("m"), direction: "in", ticketId: null, type: "text", text: "नमस्ते, हमारे केंद्र में हेडसेट काम नहीं कर रहा", createdAt: ago(51.4) },
      { messageId: id("m"), direction: "out", ticketId: null, type: "text", text: "नमस्ते! कृपया अपनी समस्या बताएं। फोटो या वीडियो भी भेज सकते हैं।", sentVia: "freeform", providerStatus: "read", createdAt: ago(51.3) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260908-0042", type: "text", text: "हेडसेट चालू नहीं हो रहा है। चार्ज करने पर भी लाल बत्ती जलती रहती है, हरी नहीं होती।", createdAt: ago(51.1) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260908-0042", type: "image", text: null, attachment: { state: "stored", mimeType: "image/jpeg", sizeBytes: 1_468_006, attempts: 1 }, createdAt: ago(51) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260908-0042", type: "text", text: "धन्यवाद। आपकी शिकायत दर्ज हो गई है — TKT-20260908-0042", sentVia: "freeform", providerStatus: "read", createdAt: ago(50.9) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260908-0042", type: "text", text: "कोई जवाब नहीं आया अभी तक? बच्चों की क्लास रुकी हुई है", createdAt: ago(20.4) },
    ],
    events: [
      { eventId: id("e"), type: "created", actor: "bot", note: null, at: ago(50.9) },
      { eventId: id("e"), type: "sla_flagged", actor: "system", note: "24h with no first response", at: ago(26.9) },
      { eventId: id("e"), type: "sla_flagged", actor: "system", note: "48h with no first response", at: ago(2.9) },
    ],
  },
  {
    ticketId: "TKT-20260908-0041",
    waNumber: "919440287731",
    contactName: "Lakshmi Reddy",
    centreName: "AWC 12, Warangal Rural",
    serviceId: "poshan-ai",
    serviceName: "Poshan AI",
    categoryId: "data-loss",
    categoryLabel: "Data not saving",
    language: "te",
    description:
      "పిల్లల ఎత్తు బరువు నమోదు చేసిన తర్వాత సేవ్ కావడం లేదు. మళ్ళీ తెరిస్తే ఖాళీగా ఉంటుంది.",
    attachmentCount: 1,
    status: "open",
    slaState: "reminder_due",
    resolution: null,
    createdAt: ago(28),
    updatedAt: ago(3.6),
    firstResponseAt: null,
    resolvedAt: null,
    closedAt: null,
    lastInboundAt: ago(3.6),
    messages: [
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260908-0041", type: "text", text: "పిల్లల ఎత్తు బరువు నమోదు చేసిన తర్వాత సేవ్ కావడం లేదు. మళ్ళీ తెరిస్తే ఖాళీగా ఉంటుంది.", createdAt: ago(27.9) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260908-0041", type: "text", text: "ధన్యవాదాలు. మీ ఫిర్యాదు నమోదు అయింది — TKT-20260908-0041", sentVia: "freeform", providerStatus: "delivered", createdAt: ago(27.8) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260908-0041", type: "text", text: "ఇవాళ కూడా అదే సమస్య", createdAt: ago(3.7) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260908-0041", type: "image", text: null, attachment: { state: "pending", mimeType: "image/jpeg", sizeBytes: null, attempts: 1 }, createdAt: ago(3.6) },
    ],
    events: [
      { eventId: id("e"), type: "created", actor: "bot", note: null, at: ago(27.8) },
      { eventId: id("e"), type: "sla_flagged", actor: "system", note: "24h with no first response", at: ago(3.8) },
      { eventId: id("e"), type: "message_added", actor: "bot", note: null, at: ago(3.7) },
    ],
  },
  {
    ticketId: "TKT-20260907-0038",
    waNumber: "919812336047",
    contactName: "Meena Kumari",
    centreName: "AWC 7, Sector 21, Gurugram",
    serviceId: "german-ai",
    serviceName: "German AI",
    categoryId: "audio",
    categoryLabel: "Audio not playing",
    language: "hi",
    description: "लेसन 4 में आवाज़ नहीं आ रही। बाकी सब ठीक चल रहा है, सिर्फ ऑडियो बंद है।",
    attachmentCount: 0,
    status: "in_progress",
    slaState: "ok",
    resolution: null,
    createdAt: ago(30),
    updatedAt: ago(4.1),
    firstResponseAt: ago(4.2),
    resolvedAt: null,
    closedAt: null,
    lastInboundAt: ago(26.5),
    messages: [
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260907-0038", type: "text", text: "लेसन 4 में आवाज़ नहीं आ रही। बाकी सब ठीक चल रहा है, सिर्फ ऑडियो बंद है।", createdAt: ago(29.9) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260907-0038", type: "text", text: "धन्यवाद। आपकी शिकायत दर्ज हो गई है — TKT-20260907-0038", sentVia: "freeform", providerStatus: "read", createdAt: ago(29.8) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260907-0038", type: "text", text: "ठीक है, इंतज़ार कर रही हूँ", createdAt: ago(26.5) },
    ],
    events: [
      { eventId: id("e"), type: "created", actor: "bot", note: null, at: ago(29.8) },
      { eventId: id("e"), type: "status_changed", from: "open", to: "in_progress", actor: "admin", note: null, at: ago(4.2) },
      { eventId: id("e"), type: "note", actor: "admin", note: "Reproduced on build 2.3.1 — audio codec missing", at: ago(4.1) },
    ],
  },
  {
    ticketId: "TKT-20260907-0036",
    waNumber: "919025714488",
    contactName: "Rajeshwari M",
    centreName: "AWC 3, Tiruvallur",
    serviceId: "anganwadi-vr",
    serviceName: "Anganwadi VR",
    categoryId: "controller",
    categoryLabel: "Controller not pairing",
    language: "ta",
    description:
      "கண்ட்ரோலர் இணைக்கப்படவில்லை. விளக்கு சிமிட்டுகிறது ஆனால் இணைப்பு ஏற்படவில்லை.",
    attachmentCount: 0,
    status: "in_progress",
    slaState: "ok",
    resolution: null,
    createdAt: ago(9),
    updatedAt: ago(1.2),
    firstResponseAt: ago(1.2),
    resolvedAt: null,
    closedAt: null,
    lastInboundAt: ago(8.8),
    messages: [
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260907-0036", type: "text", text: "கண்ட்ரோலர் இணைக்கப்படவில்லை. விளக்கு சிமிட்டுகிறது ஆனால் இணைப்பு ஏற்படவில்லை.", createdAt: ago(8.9) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260907-0036", type: "text", text: "நன்றி. உங்கள் புகார் பதிவு செய்யப்பட்டது — TKT-20260907-0036", sentVia: "freeform", providerStatus: "delivered", createdAt: ago(8.8) },
    ],
    events: [
      { eventId: id("e"), type: "created", actor: "bot", note: null, at: ago(8.8) },
      { eventId: id("e"), type: "status_changed", from: "open", to: "in_progress", actor: "admin", note: null, at: ago(1.2) },
    ],
  },
  {
    ticketId: "TKT-20260906-0031",
    waNumber: "919833120945",
    contactName: "Priya Sharma",
    centreName: "AWC 18, Andheri East, Mumbai",
    serviceId: "poshan-ai",
    serviceName: "Poshan AI",
    categoryId: "crash",
    categoryLabel: "App crashes",
    language: "en",
    description:
      "App closes every time I try to upload a child's photo. Happens on all phones at our centre.",
    attachmentCount: 0,
    status: "resolved",
    slaState: "ok",
    resolution: {
      text: "Fixed in version 2.4. Please update from the Play Store and try again.",
      sentAt: ago(1.1),
      deliveryState: "failed",
      attempts: 1,
    },
    createdAt: ago(40),
    updatedAt: ago(1.05),
    firstResponseAt: ago(6),
    resolvedAt: ago(1.1),
    closedAt: null,
    lastInboundAt: ago(38.5),
    messages: [
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260906-0031", type: "text", text: "App closes every time I try to upload a child's photo. Happens on all phones at our centre.", createdAt: ago(39.9) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260906-0031", type: "text", text: "Thank you. Your report has been logged — TKT-20260906-0031", sentVia: "freeform", providerStatus: "read", createdAt: ago(39.8) },
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260906-0031", type: "text", text: "ok", createdAt: ago(38.5) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260906-0031", type: "text", text: "Fixed in version 2.4. Please update from the Play Store and try again.", sentVia: "template", providerStatus: "failed", createdAt: ago(1.1) },
    ],
    events: [
      { eventId: id("e"), type: "created", actor: "bot", note: null, at: ago(39.8) },
      { eventId: id("e"), type: "status_changed", from: "open", to: "in_progress", actor: "admin", note: null, at: ago(6) },
      { eventId: id("e"), type: "resolution_sent", actor: "admin", note: null, at: ago(1.1) },
      { eventId: id("e"), type: "media_failed", actor: "system", note: "Template not approved for this language — send failed", at: ago(1.05) },
    ],
  },
  {
    ticketId: "TKT-20260906-0029",
    waNumber: "919448552210",
    contactName: "Anitha K",
    centreName: "AWC 9, Mysuru North",
    serviceId: "anganwadi-vr",
    serviceName: "Anganwadi VR",
    categoryId: "content",
    categoryLabel: "Content not loading",
    language: "en",
    description: "The learning modules do not load past the first screen.",
    attachmentCount: 0,
    status: "closed",
    slaState: "ok",
    resolution: {
      text: "Cleared. The centre's Wi-Fi was blocking our media server; your coordinator has updated the router settings.",
      sentAt: ago(20),
      deliveryState: "delivered",
      attempts: 1,
    },
    createdAt: ago(62),
    updatedAt: ago(19.9),
    firstResponseAt: ago(31),
    resolvedAt: ago(20),
    closedAt: ago(19.9),
    lastInboundAt: ago(60),
    messages: [
      { messageId: id("m"), direction: "in", ticketId: "TKT-20260906-0029", type: "text", text: "The learning modules do not load past the first screen.", createdAt: ago(61.9) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260906-0029", type: "text", text: "Thank you. Your report has been logged — TKT-20260906-0029", sentVia: "freeform", providerStatus: "read", createdAt: ago(61.8) },
      { messageId: id("m"), direction: "out", ticketId: "TKT-20260906-0029", type: "text", text: "Cleared. The centre's Wi-Fi was blocking our media server; your coordinator has updated the router settings.", sentVia: "template", providerStatus: "delivered", createdAt: ago(20) },
    ],
    events: [
      { eventId: id("e"), type: "created", actor: "bot", note: null, at: ago(61.8) },
      { eventId: id("e"), type: "status_changed", from: "open", to: "in_progress", actor: "admin", note: null, at: ago(31) },
      { eventId: id("e"), type: "resolution_sent", actor: "admin", note: null, at: ago(20) },
      { eventId: id("e"), type: "delivered", actor: "system", note: "Delivery receipt received", at: ago(19.9) },
    ],
  },
]

export const nextId = id
